name = "worker"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-10-19"
kv_namespaces = [ 
         { binding = "posts_kv",  preview_id = "704039c1e70440999c06be2d7db66fdb", id = "6f3ba043445248418522b8aa303491d0" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

